apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example
spec:
  selector:
    app: example-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
